### ISSUE TITLE
Install fail on Windows

### ISSUE THREAD

**Issue by pepoluan** [davidmarble/pywin#3]
The Python versions I had on my computer are `2.7.11` and `3.5.1`, with the following situation
- `py.exe`'s default version is `2.7.11`
- PATH references `C:\Python35` and `C:\Python35\Scripts\` (the install location of `3.5.11`)

Upon running `pip install pywin` I got the following error:

```
Collecting pywin
  Downloading pywin-0.3.1.zip
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz
    Extracting in C:\Users\PANDUP~1\AppData\Local\Temp\tmp560hmqbz
    Traceback (most recent call last):
      File "C:\Users\PANDUP~1\AppData\Local\Temp\pip-build-2gp3oqis\pywin\distribute_setup.py", line 150, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\PANDUP~1\AppData\Local\Temp\pip-build-2gp3oqis\pywin\setup.py", line 4, in <module>
        use_setuptools()
      File "C:\Users\PANDUP~1\AppData\Local\Temp\pip-build-2gp3oqis\pywin\distribute_setup.py", line 152, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "C:\Users\PANDUP~1\AppData\Local\Temp\pip-build-2gp3oqis\pywin\distribute_setup.py", line 132, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "C:\Users\PANDUP~1\AppData\Local\Temp\pip-build-2gp3oqis\pywin\distribute_setup.py", line 105, in _build_egg
        _extractall(tar)
      File "C:\Users\PANDUP~1\AppData\Local\Temp\pip-build-2gp3oqis\pywin\distribute_setup.py", line 500, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\PANDUP~1\AppData\Local\Temp\pip-build-2gp3oqis\pywin
```

Changing `py.exe`'s Python version to `3` using the command `set PY_PYTHON=3` still resulted in the same error.

So I tried using `easy_install pywin`, and got the following result:

```
Searching for pywin
Reading https://pypi.python.org/simple/pywin/
Best match: pywin 0.3.1
Downloading https://pypi.python.org/packages/source/p/pywin/pywin-0.3.1.zip#md5=54aa878622bccc6aba0530fe86d74732
Processing pywin-0.3.1.zip
Writing C:\Users\PANDUP~1\AppData\Local\Temp\easy_install-5lgi2pmt\pywin-0.3.1\setup.cfg
Running pywin-0.3.1\setup.py -q bdist_egg --dist-dir C:\Users\PANDUP~1\AppData\Local\Temp\easy_install-5lgi2pmt\pywin-0.3.1\egg-dist-tmp-23t6uxhl
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz
Extracting in C:\Users\PANDUP~1\AppData\Local\Temp\easy_install-5lgi2pmt\pywin-0.3.1\temp\tmpb6s9y_xc
error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\PANDUP~1\\AppData\\Local\\Temp\\easy_install-5lgi2pmt\\pywin-0.3.1\\distribute-0.6.35.tar.gz'
```

Finally I used the last method of running `setup.py install`. Ended up with the same error as `pip install pywin` above.

**Comment by gtalarico** [comment]
same here.
Here is the stack:

```

C:\Users\gtalarico\Dropbox\Shared\dev-ubuntu\repos\foldify\foldify>pip install pywin
Collecting pywin
  Downloading pywin-0.3.1.zip
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz
    Extracting in C:\Users\GTALAR~1\AppData\Local\Temp\tmpn5h6dzsv
    Traceback (most recent call last):
      File "C:\Users\GTALAR~1\AppData\Local\Temp\pip-build-t2fe3c_u\pywin\distribute_setup.py", line 150, in use_setupto
ols
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\GTALAR~1\AppData\Local\Temp\pip-build-t2fe3c_u\pywin\setup.py", line 4, in <module>
        use_setuptools()
      File "C:\Users\GTALAR~1\AppData\Local\Temp\pip-build-t2fe3c_u\pywin\distribute_setup.py", line 152, in use_setupto
ols
        return _do_download(version, download_base, to_dir, download_delay)
      File "C:\Users\GTALAR~1\AppData\Local\Temp\pip-build-t2fe3c_u\pywin\distribute_setup.py", line 132, in _do_downloa
d
        _build_egg(egg, tarball, to_dir)
      File "C:\Users\GTALAR~1\AppData\Local\Temp\pip-build-t2fe3c_u\pywin\distribute_setup.py", line 105, in _build_egg
        _extractall(tar)
      File "C:\Users\GTALAR~1\AppData\Local\Temp\pip-build-t2fe3c_u\pywin\distribute_setup.py", line 500, in _extractall

        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\GTALAR~1\AppData\Local\Temp\pip-build-t2fe3c_u\p
ywin\

```

**Comment by askpatrickw** [comment]
👍  - I also see this

**Comment by ololoru** [comment]
Try the following fork - https://github.com/prestonr83/pywin

**Comment by seanvree** [comment]
Yup, I'm having this issue too.

**Comment by so2bin** [comment]
so have anyone resolved this issue?

**Comment by fx-kirin** [comment]
ololoru's forked repo solved the installation problem.
