### ISSUE TITLE
"IOError: Could not build the egg."

### ISSUE THREAD

**Issue by seanvree** [davidmarble/pywin#4]
Running python  2.7.12 on Windows 10 U
setuptools (32.0.0)

Can't get pywin to install. 

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd c:\

c:\>git clone git://github.com/davidmarble/pywin.git

Cloning into 'pywin'...
remote: Counting objects: 97, done.
Receiving objects:  59% (58/97)    0 (delta 0), pack-reused 97Receiving objects:  55% (54/97)
Receiving objects: 100% (97/97), 39.12 KiB | 0 bytes/s, done.
Resolving deltas: 100% (47/47), done.

c:\>cd pywin

c:\pywin>python setup.py install

Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz
Extracting in c:\users\admini~1\appdata\local\temp\tmpladtrj
Now working in c:\users\admini~1\appdata\local\temp\tmpladtrj\distribute-0.6.35
Building a Distribute egg in c:\pywin
Traceback (most recent call last):
  File "setup.py", line 248, in <module>
    scripts = scripts,
  File "C:\Python27\lib\distutils\core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "c:\users\admini~1\appdata\local\temp\tmpladtrj\distribute-0.6.35\setuptools\dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "C:\Python27\lib\distutils\dist.py", line 287, in __init__
    self.finalize_options()
  File "c:\users\admini~1\appdata\local\temp\tmpladtrj\distribute-0.6.35\setuptools\dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "c:\users\admini~1\appdata\local\temp\tmpladtrj\distribute-0.6.35\pkg_resources.py", line 2027, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "c:\users\admini~1\appdata\local\temp\tmpladtrj\distribute-0.6.35\pkg_resources.py", line 2237, in requires
    dm = self._dep_map
  File "c:\users\admini~1\appdata\local\temp\tmpladtrj\distribute-0.6.35\pkg_resources.py", line 2466, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "c:\users\admini~1\appdata\local\temp\tmpladtrj\distribute-0.6.35\pkg_resources.py", line 2499, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "c:\users\admini~1\appdata\local\temp\tmpladtrj\distribute-0.6.35\pkg_resources.py", line 2496, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "c:\users\admini~1\appdata\local\temp\tmpladtrj\distribute-0.6.35\_markerlib\markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
c:\pywin\distribute-0.6.35-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    use_setuptools()
  File "c:\pywin\distribute_setup.py", line 152, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "c:\pywin\distribute_setup.py", line 132, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "c:\pywin\distribute_setup.py", line 123, in _build_egg
    raise IOError('Could not build the egg.')
IOError: Could not build the egg.

Any ideas?

**Comment by seanvree** [comment]
nevermind, dupe of https://github.com/davidmarble/pywin/issues/2
